# Generated by Django 6.0.2 on 2026-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_reportpage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='stat_announcement_count',
            field=models.CharField(blank=True, default='', help_text='例如：4235 条', max_length=50, verbose_name='采购公告数量'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='stat_budget_total',
            field=models.CharField(blank=True, default='', help_text='例如：153,674 万元', max_length=50, verbose_name='预算金额'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='stat_buyer_count',
            field=models.CharField(blank=True, default='', help_text='例如：268 家', max_length=50, verbose_name='采购单位数量'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='stat_region_count',
            field=models.CharField(blank=True, default='', help_text='例如：31 个地区', max_length=50, verbose_name='采购地区数量'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='stat_transaction_total',
            field=models.CharField(blank=True, default='', help_text='例如：125,809 万元', max_length=50, verbose_name='成交总额'),
        ),
    ]
