# Generated by Django 6.0.2 on 2026-04-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_reportpage_stat_announcement_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpage',
            name='market_trend_analysis',
        ),
    ]
