# Generated by Django 6.0.2 on 2026-04-03 11:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_remove_reportpage_market_trend_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBuyerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('buyer_name', models.CharField(max_length=255, verbose_name='采购单位')),
                ('region', models.CharField(blank=True, default='-', max_length=100, verbose_name='所属地区')),
                ('project_count', models.IntegerField(default=0, verbose_name='项目数(项)')),
                ('budget_amount', models.CharField(blank=True, default='-', max_length=50, verbose_name='预算金额(万元)')),
                ('transaction_amount', models.CharField(blank=True, default='-', max_length=50, verbose_name='成交金额(万元)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_buyers', to='reports.reportpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
