# Generated by Django 6.0.2 on 2026-04-03 11:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_topbuyeranalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('region_name', models.CharField(help_text='例如：浙江、湖南、四川', max_length=50, verbose_name='地区名称')),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='采购金额(万元)')),
                ('project_count', models.IntegerField(default=0, verbose_name='项目数量(个)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_purchase_data', to='reports.reportpage')),
            ],
            options={
                'verbose_name': '地区采购数据',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
