# Generated by Django 6.0.2 on 2026-04-03 11:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_regionpurchasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementMethodShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('method_name', models.CharField(help_text='例如：公开招标、竞争性磋商、单一来源', max_length=100, verbose_name='采购方式')),
                ('project_count_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='项目数量占比(%)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_methods', to='reports.reportpage')),
            ],
            options={
                'verbose_name': '采购方式占比',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopSupplierShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('supplier_name', models.CharField(max_length=255, verbose_name='供应商名称')),
                ('project_count_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='项目数量占比(%)')),
                ('transaction_amount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='成交金额占比(%)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_suppliers', to='reports.reportpage')),
            ],
            options={
                'verbose_name': '供应商市场份额',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
