# Generated by Codex on 2026-04-05

from django.db import migrations, models


def set_analysis_type_to_analysis(apps, schema_editor):
    ReportPage = apps.get_model('reports', 'ReportPage')
    ReportPage.objects.exclude(analysis_type='分析').update(analysis_type='分析')


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_procurementmethodshare_topsuppliershare'),
    ]

    operations = [
        migrations.RunPython(
            set_analysis_type_to_analysis,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='reportpage',
            name='analysis_type',
            field=models.CharField(
                choices=[('分析', '分析')],
                default='分析',
                max_length=50,
                verbose_name='分析',
            ),
        ),
    ]
