# Generated by Django 6.0.2 on 2026-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_reportpage_analysis_type_analysis_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='analysis_keywords',
            field=models.TextField(blank=True, default='', verbose_name='分析关键词'),
        ),
    ]
