# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_reportpage_analysis_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='market_trend_analysis',
            field=models.TextField(blank=True, default='', verbose_name='市场交易趋势'),
            preserve_default=False,
        ),
    ]
